// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz8L1LQ3BdV4RH9KQsWhztuNeOVOm4zJc',
    appId: '1:500088335930:web:3a6fa368f9f5275fc0cf03',
    messagingSenderId: '500088335930',
    projectId: 'git-action-test-cb97e',
    authDomain: 'git-action-test-cb97e.firebaseapp.com',
    storageBucket: 'git-action-test-cb97e.appspot.com',
    measurementId: 'G-MTKVR81CNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJOSUuMKPkK8btSNatHBENDAeDXfkZJ1I',
    appId: '1:500088335930:android:76d901c5d93af445c0cf03',
    messagingSenderId: '500088335930',
    projectId: 'git-action-test-cb97e',
    storageBucket: 'git-action-test-cb97e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBECEHm7ZS6DL3WQk62wiDdxRNA2RNe7Zk',
    appId: '1:500088335930:ios:aaa03c8b338d1b10c0cf03',
    messagingSenderId: '500088335930',
    projectId: 'git-action-test-cb97e',
    storageBucket: 'git-action-test-cb97e.appspot.com',
    iosBundleId: 'com.example.gitActionTest.hj',
  );
}
